#!/usr/bin/perl

=pod

Begin-Doc
Name: AddAdminOption
Type: RPC Perl Script
Location: Adds a admin option to the host
CGI-Parameters: key is 'host' value is hostname, key is 'option'
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            my $host   = $opts{host};
            my $option = $opts{option};

            return $admin->AddAdminOption( $host, $option );
        }
    );

    $rpc->FinishReturn($res);
}
