#!/usr/bin/perl

=pod

Begin-Doc
Name: AddAdminOption
Type: RPC Perl Script
Location: Adds a admin option to the host
CGI-Parameters: key is 'host' value is hostname, key is 'option'
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc  = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        my $host   = $opts{host};
        my $option = $opts{option};

        return $admin->AddAdminOption( $host, $option );
    }
);

$rpc->Finish($res);
