#!/usr/bin/perl

=pod

Begin-Doc
Name: AddEther
Type: RPC Perl Script
Location: Adds ethernet address to host
CGI-Parameters: keys are 'host' and 'ether'
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            my $host  = $opts{host};
            my $ether = $opts{ether};
            return $admin->AddEther( $host, $ether );
        }
    );

    $rpc->FinishReturn($res);
}
