#!/usr/bin/perl

=pod

Begin-Doc
Name: AddHostOption
Type: RPC Perl Script
Location: Adds a host option to the host
CGI-Parameters: key is 'host' value is hostname, key is 'option'
SimpleRPC-Return: none
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

my $rpc  = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        my $host   = $opts{host};
        my $option = $opts{option};

        return $admin->AddHostOption( $host, $option );
    }
);

$rpc->Finish($res);
