#!/usr/bin/perl

=pod

Begin-Doc
Name: AutoAllocateVMWareAddr
Type: RPC Perl Script
Location: Allocates vmware mac addr for host
CGI-Parameters: key is 'host' value is hostname
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
		my $host = $opts{host};
        return $admin->AutoAllocateVMWareAddr($host);
    }
);

$rpc->Finish($res);