#!/usr/bin/perl

=pod

Begin-Doc
Name: CreateHost
Type: RPC Perl Script
Location: Creates a host
CGI-Parameters: see NetDBAdmin module CreateHost routine for parameters
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new UMR::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        return $admin->CreateHost(%opts);
    }
);

$rpc->Finish($res);