#!/usr/bin/perl

=pod

Begin-Doc
Name: CreateHost
Type: RPC Perl Script
Location: Creates a host
CGI-Parameters: see NetDBAdmin module CreateHost routine for parameters
SimpleRPC-Return: none
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

my $rpc  = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        return $admin->CreateHost(%opts);
    }
);

$rpc->Finish($res);
