#!/usr/bin/perl

=pod

Begin-Doc
Name: DeleteUtilityCNames
Type: RPC Perl Script
Description: deletes utility cnames
CGI-Parameters: host, may be repeated
SimpleRPC-Return: error message on failure
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new Local::SimpleRPC::Server;
$rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my @hosts = $rpc->param("host");

my $res = $rpc->Try(
    sub {
        return $admin->DeleteUtilityCNames(@hosts);
    }
);

$rpc->Finish(%$res);