#!/usr/bin/perl

=pod

Begin-Doc
Name: DeleteUtilityCNames
Type: RPC Perl Script
Description: deletes utility cnames
CGI-Parameters: host, may be repeated
SimpleRPC-Return: error message on failure
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    $rpc->RequirePriv("rpc:netdb:userops");

    my $admin = new RPC::NetDBAdmin;

    my @hosts = $rpc->multi_param("host");

    my $res = $rpc->Try(
        sub {
            return $admin->DeleteUtilityCNames(@hosts);
        }
    );

    $rpc->FinishReturn(%$res);
}
