#!/usr/bin/perl

=pod

Begin-Doc
Name: DeleteHost
Type: RPC Perl Script
Location: Deletes a host
CGI-Parameters: host - hostname
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            my $host = $opts{host};
            return $admin->DeleteHost($host);
        }
    );

    $rpc->FinishReturn($res);
}
