#!/usr/bin/perl

=pod

Begin-Doc
Name: GetAdminOptions
Type: RPC Perl Script
Description: Returns admin options for each host
CGI-Parameters: host - host to search for, can be repeated
SimpleRPC-Return: hash - keyed on hostname, values are arrays of admin options
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new UMR::SimpleRPC::Server( pretty => 1 );
$rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin  = new RPC::NetDBAdmin;

my @hosts = $rpc->param("host");

my %res_by_host = ();
foreach my $host (@hosts) {
    my $res = $rpc->Try(
        sub {
            return $admin->GetAdminOptions($host);
        }
    );
    $res_by_host{$host} = $res;
}

$rpc->Finish( {%res_by_host} );