#!/usr/bin/perl

=pod

Begin-Doc
Name: GetAdminOptions
Type: RPC Perl Script
Description: Returns admin options for each host
CGI-Parameters: host - host to search for, can be repeated
SimpleRPC-Return: hash - keyed on hostname, values are arrays of admin options
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    $rpc->RequirePriv("rpc:netdb:userops");

    my $admin = new RPC::NetDBAdmin;

    my @hosts = $rpc->multi_param("host");

    my %res_by_host = ();
    foreach my $host (@hosts) {
        my $res = $rpc->Try(
            sub {
                return $admin->GetAdminOptions($host);
            }
        );
        $res_by_host{$host} = $res;
    }

    $rpc->FinishReturn( {%res_by_host} );
}
