#!/usr/bin/perl

=pod

Begin-Doc
Name: GetHostMetadataField
Type: RPC Perl Script
Location: Gets metadata field from netdb for host
CGI-Parameters: key is 'host' value is hostname, key is 'field' value is fieldname
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("rpc:netdb:userops");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            my $host  = $opts{host};
            my $field = $opts{field};

            return $admin->GetHostMetadataField( $host, $field );
        }
    );

    $rpc->FinishReturn($res);
}
