#!/usr/bin/perl

=pod

Begin-Doc
Name: GetHostsWithAdminOption
Type: RPC Perl Script
Description: Returns list of hosts having each requested admin option
CGI-Parameters: option - option to search on, can be repeated
SimpleRPC-Return: hash - keyed on option, values are arrays of hostnames
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();
    $rpc->RequirePriv("rpc:netdb:queryinfo");

    my $dhcp    = new NetMaint::DHCP;
    my @options = $rpc->multi_param("option");

    my %res_by_option = ();
    foreach my $option (@options) {
        my $res = $rpc->Try(
            sub {
                return $dhcp->SearchByAdminOption($option);
            }
        );
        $res_by_option{$option} = $res;
    }

    $rpc->FinishReturn( {%res_by_option} );
}
