#!/usr/bin/perl

=pod

Begin-Doc
Name: GetHostMetadataFieldAll
Type: RPC Perl Script
Location: Gets metadata field from netdb for all hosts
CGI-Parameters: key is 'field' value is fieldname
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc  = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        my $field = $opts{field};

        return $admin->GetHostMetadataFieldAll($field);
    }
);

$rpc->Finish($res);
