#!/usr/bin/perl

=pod

Begin-Doc
Name: GetHostsWithDHCPOption
Type: RPC Perl Script
Description: Returns list of hosts having each requested dhcp option
CGI-Parameters: option - option to search on, can be repeated
SimpleRPC-Return: hash - keyed on option, values are arrays of hostnames
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new UMR::SimpleRPC::Server();
$rpc->Init();
$rpc->RequirePriv("rpc:netdb:queryinfo");

my $dhcp = new NetMaint::DHCP;
my @options = $rpc->param("option");

my %res_by_option = ();
foreach my $option (@options) {
    my $res = $rpc->Try(
        sub {
            return $dhcp->SearchByDHCPOption($option);
        }
    );
    $res_by_option{$option} = $res;
}

$rpc->Finish( {%res_by_option} );