#!/usr/bin/perl

=pod

Begin-Doc
Name: GetUtilityCNames
Type: RPC Perl Script
Description: Returns utility cnames in a particular group
CGI-Parameters: group, may be repeated
SimpleRPC-Return: hash of hashes: group => cname => target
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my @groups = $rpc->multi_param("group");

    my $res = $rpc->Try(
        sub {
            return $admin->GetUtilityCNames(@groups);
        }
    );

    $rpc->FinishReturn(%$res);
}
