#!/usr/bin/perl

=pod

Begin-Doc
Name: GetUtilityCNames
Type: RPC Perl Script
Description: Returns utility cnames in a particular group
CGI-Parameters: group, may be repeated
SimpleRPC-Return: hash of hashes: group => cname => target
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

my $rpc = new Local::SimpleRPC::Server;
$rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my @groups = $rpc->param("group");

my $res = $rpc->Try(
    sub {
        return $admin->GetUtilityCNames(@groups);
    }
);

$rpc->Finish(%$res);
