#!/usr/bin/perl

=pod

Begin-Doc
Name: RemoveEther
Type: RPC Perl Script
Location: Removes ethernet address to host
CGI-Parameters: keys are 'host' and 'ether'
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new UMR::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
		my $host = $opts{host};
		my $ether = $opts{ether};
        return $admin->RemoveEther($host, $ether);
    }
);

$rpc->Finish($res);