#!/usr/bin/perl

=pod

Begin-Doc
Name: RemoveHostOption
Type: RPC Perl Script
Location: Removes a host option to the host
CGI-Parameters: key is 'host' value is hostname, key is 'option'
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new UMR::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
		my $host = $opts{host};
		my $option = $opts{option};

        return $admin->RemoveHostOption($host, $option);
    }
);

$rpc->Finish($res);