#!/usr/bin/perl

=pod

Begin-Doc
Name: RemoveEther
Type: RPC Perl Script
Location: Removes ethernet address to host
CGI-Parameters: keys are 'host' and 'ether'
SimpleRPC-Return: none
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

my $rpc  = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
        my $host  = $opts{host};
        my $ether = $opts{ether};
        return $admin->RemoveEther( $host, $ether );
    }
);

$rpc->Finish($res);
