#!/usr/bin/perl

=pod

Begin-Doc
Name: SetAdminLock
Type: RPC Perl Script
Location: Sets admin lock status for a host
CGI-Parameters: key is hostname, value is lock status (non-zero is locked)
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            foreach my $key ( sort( keys(%opts) ) ) {
                $admin->SetAdminLock( $key, $opts{$key} );
            }
            return {};
        }
    );

    $rpc->FinishReturn($res);
}
