#!/usr/bin/perl

=pod

Begin-Doc
Name: SetHostDescription
Type: RPC Perl Script
Description: Sets description info from netdb for host
CGI-Parameters: key is 'host' value is hostname, key is 'description'
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
		my $host = $opts{host};
		my $desc = $opts{description};

        return $admin->SetHostDescription($host, $desc);
    }
);

$rpc->Finish($res);