#!/usr/bin/perl

=pod

Begin-Doc
Name: SetHostLocation
Type: RPC Perl Script
Location: Sets description info from netdb for host
CGI-Parameters: key is 'host' value is hostname, key is 'location'
SimpleRPC-Return: none
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc = new Local::SimpleRPC::Server;
my %opts = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $res = $rpc->Try(
    sub {
		my $host = $opts{host};
		my $loc = $opts{location};

        return $admin->SetHostLocation($host, $loc);
    }
);

$rpc->Finish($res);