#!/usr/bin/perl

=pod

Begin-Doc
Name: SetHostLocation
Type: RPC Perl Script
Location: Sets description info from netdb for host
CGI-Parameters: key is 'host' value is hostname, key is 'location'
SimpleRPC-Return: none
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my %opts = $rpc->Init();

    $rpc->RequirePriv("netmgr-user");

    my $admin = new RPC::NetDBAdmin;

    my $res = $rpc->Try(
        sub {
            my $host = $opts{host};
            my $loc  = $opts{location};

            return $admin->SetHostLocation( $host, $loc );
        }
    );

    $rpc->FinishReturn($res);
}
