#!/usr/bin/perl

=pod

Begin-Doc
Name: UpdateUtilityCName
Type: RPC Perl Script
Description: updates targets for or creates utility cname for a single host
CGI-Parameters: host and target, may not be repeated at this time
SimpleRPC-Return: error message on failure
End-Doc

=cut

use lib "/local/perllib/libs";
use lib "/local/spirentlib/libs";
use lib "/local/netdb/libs";
use Local::SimpleRPC;
use RPC::NetDBAdmin;
use strict;

my $rpc    = new Local::SimpleRPC::Server;
my @params = $rpc->Init();

$rpc->RequirePriv("rpc:netdb:userops");

my $admin = new RPC::NetDBAdmin;

my $host   = $rpc->param("host");
my $target = $rpc->param("target");

my $res = $rpc->Try(
    sub {
        return $admin->UpdateUtilityCName( $host, $target );
    }
);

$rpc->Finish($res);