#!/usr/bin/perl

=pod

Begin-Doc
Name: UpdateUtilityCName
Type: RPC Perl Script
Description: updates targets for or creates utility cname for a single host
CGI-Parameters: host and target, may not be repeated at this time
SimpleRPC-Return: error message on failure
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBAdmin;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    my @params = $rpc->Init();

    $rpc->RequirePriv("rpc:netdb:userops");

    my $admin = new RPC::NetDBAdmin;

    my $host   = $rpc->param("host");
    my $target = $rpc->param("target");

    my $res = $rpc->Try(
        sub {
            return $admin->UpdateUtilityCName( $host, $target );
        }
    );

    $rpc->FinishReturn($res);
}
