alter table dns_a add column etime datetime;
alter table dns_aaaa add column etime datetime;
alter table dns_cname add column etime datetime;
alter table dns_mx add column etime datetime;
alter table dns_ns add column etime datetime;
alter table dns_ptr add column etime datetime;
alter table dns_srv add column etime datetime;
alter table dns_txt add column etime datetime;
alter table dns_spf add column etime datetime;
