#!/usr/bin/perl

=pod

Begin-Doc
Name: EtherToHost
Type: RPC Perl Script
Description: Returns hostname associated in netdb with a given ethernet address
CGI-Parameters: ether - ethernet address to look up, can be repeated
SimpleRPC-Return: hash, keyed on ether, value is hostname
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    my $admin  = new RPC::NetDBUser;
    my @ethers = $rpc->multi_param("ether");

    my %res_by_ether = ();
    foreach my $ether (@ethers) {
        my $host = $rpc->Try(
            sub {
                return $admin->EtherToHost($ether);
            }
        );
        $res_by_ether{$ether} = $host;
    }

    $rpc->FinishReturn( {%res_by_ether} );
}
