#!/usr/bin/perl

=pod

Begin-Doc
Name: Exists
Type: RPC Perl Script
Description: Returns if hosts exist in netdb
CGI-Parameters: host - hostname to look up, can be repeated
SimpleRPC-Return: hash keyed on hostname, value is 0/1, 1 if exists
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    my $admin = new RPC::NetDBUser;
    my @hosts = $rpc->multi_param("host");

    my %res_by_host = ();
    foreach my $host (@hosts) {
        my $res = $rpc->Try(
            sub {
                return $admin->ValidFQDN($host);
            }
        );
        $res_by_host{$host} = $res;
    }

    $rpc->FinishReturn( {%res_by_host} );
}
