#!/usr/bin/perl

=pod

Begin-Doc
Name: GetSubnets
Type: RPC Perl Script
Description: Returns subnet information
CGI-Parameters: none
SimpleRPC-Return: hash keyed on subnet identifier, values are hashes, keyed on description, mask, vlan, gateway, template
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

my $rpc = new Local::SimpleRPC::Server;
$rpc->Init();

my $admin = new RPC::NetDBUser;

my $res = $rpc->Try(
    sub {
        return $admin->GetSubnets();
    }
);

$rpc->Finish($res);
