#!/usr/bin/perl

=pod

Begin-Doc
Name: GetVLANs
Type: RPC Perl Script
Description: Returns vlan information
CGI-Parameters: none
SimpleRPC-Return: hash keyed on vlan identifier, values are hashes, with single key 'name'
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    my $admin = new RPC::NetDBUser;

    my $res = $rpc->Try(
        sub {
            return $admin->GetVLANs();
        }
    );

    $rpc->FinishReturn($res);
}
