#!/usr/bin/perl

=pod

Begin-Doc
Name: GetVLANs
Type: RPC Perl Script
Description: Returns vlan information
CGI-Parameters: none
SimpleRPC-Return: hash keyed on vlan identifier, values are hashes, with single key 'name'
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

my $rpc = new Local::SimpleRPC::Server;
$rpc->Init();

my $admin = new RPC::NetDBUser;

my $res = $rpc->Try(
    sub {
        return $admin->GetVLANs();
    }
);

$rpc->Finish($res);
