#!/usr/bin/perl

=pod

Begin-Doc
Name: HostToOwner
Type: RPC Perl Script
Description: Returns owner userid associated in netdb with a given host
CGI-Parameters: host - host to look up, can be repeated
SimpleRPC-Return: hash, keyed on hostname, value is userid
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    my $admin = new RPC::NetDBUser;
    my @hosts = $rpc->multi_param("host");

    my %res_by_host = ();
    foreach my $host (@hosts) {
        my $res = $rpc->Try(
            sub {
                return $admin->HostToOwner($host);
            }
        );
        $res_by_host{$host} = $res;
    }

    $rpc->FinishReturn( {%res_by_host} );
}
