#!/usr/bin/perl

=pod

Begin-Doc
Name: HostToEther
Type: RPC Perl Script
Description: Returns ethernet addresses associated in netdb with a given host
CGI-Parameters: host - hostname to look up, can be repeated
SimpleRPC-Return: hash keyed on hostname, value is array of ethernet addresses
End-Doc

=cut

use lib "/local/umrperl/libs";
use lib "/local/netdb/libs";
use UMR::SimpleRPC;
use RPC::NetDBUser;
use strict;

my $rpc = new UMR::SimpleRPC::Server;
$rpc->Init();

my $admin = new RPC::NetDBUser;
my @hosts = $rpc->param("host");

my %res_by_host = ();
foreach my $host (@hosts) {
    my $res = $rpc->Try(
        sub {
            return $admin->HostToEther($host);
        }
    );
    $res_by_host{$host} = $res;
}

$rpc->Finish( {%res_by_host} );