#!/usr/bin/perl

=pod

Begin-Doc
Name: MatchPartialHost
Type: RPC Perl Script
Description: Returns list of hostnames in netdb matching a partial hostname
CGI-Parameters: host - partial hostname to look up
SimpleRPC-Return: array of matching hosts
End-Doc

=cut

use strict;
use CGI::Fast;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

while ( my $cgi = CGI::Fast->new ) {
    my $rpc = new Local::SimpleRPC::Server( cgi => $cgi );
    $rpc->Init();

    my $admin = new RPC::NetDBUser;
    my $host  = $rpc->param("host");

    my @hosts = $rpc->Try(
        sub {
            return $admin->MatchPartialHost($host);
        }
    );

    $rpc->FinishReturn(@hosts);
}
