#!/usr/bin/perl

=pod

Begin-Doc
Name: OwnerToHosts
Type: RPC Perl Script
Description: Returns list of hosts owned by userid in netdb
CGI-Parameters: userid - host to look up, can be repeated
SimpleRPC-Return: hash, keyed on userid, value is array of hostnames
End-Doc

=cut

use strict;

BEGIN { do "/local/netdb/libs/init.pl"; }

use Local::SimpleRPC;
use RPC::NetDBUser;

my $rpc = new Local::SimpleRPC::Server;
$rpc->Init();

my $admin = new RPC::NetDBUser;
my @users = $rpc->param("userid");

my %res_by_user = ();
foreach my $userid (@users) {
    my $res = $rpc->Try(
        sub {
            return $admin->OwnerToHosts($userid);
        }
    );
    $res_by_user{$userid} = $res;
}

$rpc->Finish( {%res_by_user} );
